#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

int main() {
    unsigned char *realPtr = calloc(50000, 1);
    assert(realPtr != NULL);
    unsigned char *ptr = realPtr;
    ptr += 3;
    *ptr = 0;
    *ptr = 0;
    *ptr += 65;
    ptr += 3;
    *ptr = 0;
    ptr += 4;
    *ptr = 0;
    ptr -= 7;
    unsigned char v = *ptr;
    *(ptr + 7) += v;
    *(ptr + 3) += v;
    *ptr = 0;
    ptr += 3;
    v = *ptr;
    *(ptr + -3) += v;
    *ptr = 0;
    ptr -= 3;
    *ptr = 0;
    *ptr = 0;
    ptr += 2;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr -= 3;
    *ptr = 0;
    ptr += 7;
    v = *ptr;
    *(ptr + -7) += v;
    *(ptr + -4) += v;
    *ptr = 0;
    ptr -= 4;
    v = *ptr;
    *(ptr + 4) += v;
    *ptr = 0;
    ptr --;
    *ptr = 0;
    *ptr += 26;
    v = *ptr;
    *(ptr + -2) += v;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr += 5;
    *ptr = 0;
    ptr -= 8;
    v = *ptr;
    *(ptr + 8) += v;
    *(ptr + 3) += v;
    *ptr = 0;
    ptr += 3;
    v = *ptr;
    *(ptr + -3) += v;
    *ptr = 0;
    ptr -= 3;
    *ptr = 0;
    ptr += 3;
    *ptr = 0;
    ptr -= 6;
    *ptr = 0;
    ptr += 11;
    v = *ptr;
    *(ptr + -11) += v;
    *(ptr + -5) += v;
    *ptr = 0;
    ptr -= 5;
    v = *ptr;
    *(ptr + 5) += v;
    *ptr = 0;
    *ptr = 0;
    ptr -= 2;
    *ptr = 0;
    ptr += 6;
    v = *ptr;
    *(ptr + -6) += v;
    *(ptr + -4) += v;
    *ptr = 0;
    ptr -= 4;
    v = *ptr;
    *(ptr + 4) += v;
    *ptr = 0;
    ptr -= 5;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr -= 3;
    while (*ptr) {
        ptr ++;
        ++(*ptr);
        ptr += 3;
        while (*ptr) {
            --(*ptr);
            ptr -= 3;
            *ptr = 0;
            ptr ++;
            ++(*ptr);
            ptr += 2;
        }
        ptr -= 3;
        v = *ptr;
        *(ptr + 2) += v;
        *ptr = 0;
        ptr ++;
        v = *ptr;
        *(ptr + 2) += v;
        *ptr = 0;
        ptr += 2;
        --(*ptr);
        ptr -= 4;
        --(*ptr);
    }
    ptr += 3;
    while (*ptr) {
        ptr += 7;
        putchar(*ptr);
        ptr -= 7;
        *ptr = 0;
        *ptr = 0;
        ptr += 2;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr -= 3;
        *ptr = 0;
        ptr += 7;
        v = *ptr;
        *(ptr + -7) += v;
        *(ptr + -4) += v;
        *ptr = 0;
        ptr -= 4;
        v = *ptr;
        *(ptr + 4) += v;
        *ptr = 0;
        ptr --;
        *ptr = 0;
        ++(*ptr);
        v = *ptr;
        *(ptr + -2) += v;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr += 4;
        *ptr = 0;
        ptr -= 7;
        v = *ptr;
        *(ptr + 7) += v;
        *(ptr + 3) += v;
        *ptr = 0;
        ptr += 3;
        v = *ptr;
        *(ptr + -3) += v;
        *ptr = 0;
        ptr -= 3;
        *ptr = 0;
        ptr += 3;
        *ptr = 0;
        ptr -= 6;
        *ptr = 0;
        ptr += 11;
        v = *ptr;
        *(ptr + -11) += v;
        *(ptr + -5) += v;
        *ptr = 0;
        ptr -= 5;
        v = *ptr;
        *(ptr + 5) += v;
        *ptr = 0;
        *ptr = 0;
        ptr -= 2;
        *ptr = 0;
        ptr += 6;
        v = *ptr;
        *(ptr + -6) += v;
        *(ptr + -4) += v;
        *ptr = 0;
        ptr -= 4;
        v = *ptr;
        *(ptr + 4) += v;
        *ptr = 0;
        ptr -= 5;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr -= 3;
        while (*ptr) {
            ptr ++;
            ++(*ptr);
            ptr += 3;
            while (*ptr) {
                --(*ptr);
                ptr -= 3;
                *ptr = 0;
                ptr ++;
                ++(*ptr);
                ptr += 2;
            }
            ptr -= 3;
            v = *ptr;
            *(ptr + 2) += v;
            *ptr = 0;
            ptr ++;
            v = *ptr;
            *(ptr + 2) += v;
            *ptr = 0;
            ptr += 2;
            --(*ptr);
            ptr -= 4;
            --(*ptr);
        }
        ptr += 3;
    }
    *ptr = 0;
    *ptr = 0;
    *ptr += 65;
    ptr += 3;
    *ptr = 0;
    ptr += 6;
    *ptr = 0;
    ptr -= 9;
    v = *ptr;
    *(ptr + 9) += v;
    *(ptr + 3) += v;
    *ptr = 0;
    ptr += 3;
    v = *ptr;
    *(ptr + -3) += v;
    *ptr = 0;
    ptr -= 3;
    *ptr = 0;
    ptr += 3;
    *ptr = 0;
    ptr -= 6;
    *ptr = 0;
    ptr += 11;
    v = *ptr;
    *(ptr + -11) += v;
    *(ptr + -5) += v;
    *ptr = 0;
    ptr -= 5;
    v = *ptr;
    *(ptr + 5) += v;
    *ptr = 0;
    *ptr = 0;
    ptr -= 2;
    *ptr = 0;
    ptr += 8;
    v = *ptr;
    *(ptr + -8) += v;
    *(ptr + -6) += v;
    *ptr = 0;
    ptr -= 6;
    v = *ptr;
    *(ptr + 6) += v;
    *ptr = 0;
    ptr -= 5;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr ++;
    *ptr = 0;
    ptr -= 3;
    while (*ptr) {
        ptr ++;
        ++(*ptr);
        ptr += 3;
        while (*ptr) {
            --(*ptr);
            ptr -= 3;
            *ptr = 0;
            ptr ++;
            ++(*ptr);
            ptr += 2;
        }
        ptr -= 3;
        v = *ptr;
        *(ptr + 2) += v;
        *ptr = 0;
        ptr ++;
        v = *ptr;
        *(ptr + 2) += v;
        *ptr = 0;
        ptr += 2;
        --(*ptr);
        ptr -= 4;
        --(*ptr);
    }
    ptr += 3;
    while (*ptr) {
        ptr += 9;
        putchar(*ptr);
        ptr -= 9;
        *ptr = 0;
        *ptr = 0;
        ptr += 2;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr -= 3;
        *ptr = 0;
        ptr += 9;
        v = *ptr;
        *(ptr + -9) += v;
        *(ptr + -6) += v;
        *ptr = 0;
        ptr -= 6;
        v = *ptr;
        *(ptr + 6) += v;
        *ptr = 0;
        ptr --;
        *ptr = 0;
        ++(*ptr);
        v = *ptr;
        *(ptr + -2) += v;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr += 6;
        *ptr = 0;
        ptr -= 9;
        v = *ptr;
        *(ptr + 9) += v;
        *(ptr + 3) += v;
        *ptr = 0;
        ptr += 3;
        v = *ptr;
        *(ptr + -3) += v;
        *ptr = 0;
        ptr -= 3;
        *ptr = 0;
        ptr += 3;
        *ptr = 0;
        ptr -= 6;
        *ptr = 0;
        ptr += 11;
        v = *ptr;
        *(ptr + -11) += v;
        *(ptr + -5) += v;
        *ptr = 0;
        ptr -= 5;
        v = *ptr;
        *(ptr + 5) += v;
        *ptr = 0;
        *ptr = 0;
        ptr -= 2;
        *ptr = 0;
        ptr += 8;
        v = *ptr;
        *(ptr + -8) += v;
        *(ptr + -6) += v;
        *ptr = 0;
        ptr -= 6;
        v = *ptr;
        *(ptr + 6) += v;
        *ptr = 0;
        ptr -= 5;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr ++;
        *ptr = 0;
        ptr -= 3;
        while (*ptr) {
            ptr ++;
            ++(*ptr);
            ptr += 3;
            while (*ptr) {
                --(*ptr);
                ptr -= 3;
                *ptr = 0;
                ptr ++;
                ++(*ptr);
                ptr += 2;
            }
            ptr -= 3;
            v = *ptr;
            *(ptr + 2) += v;
            *ptr = 0;
            ptr ++;
            v = *ptr;
            *(ptr + 2) += v;
            *ptr = 0;
            ptr += 2;
            --(*ptr);
            ptr -= 4;
            --(*ptr);
        }
        ptr += 3;
    }
    free(realPtr);
    return 0;
}
